server:
  port: 8182

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer #la classe che deserializza la chiave, che è un long
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer #la classe che deserializza il value
  consumer-group-id: twitter-topic-consumer
  auto-offset-reset: earliest #significa che vogliamo iniziare dall inizio di una partizione
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true #questa property permette di leggere i dati a batches
  auto-startup: false #mettendo a false significa che si vuole iniziare  a leggere dai topic solo dopo aver controllato che siano già attivi
  concurrency-level: 3 #generalmente si setta come il numero di partitions per ottimizzare la concorrenza e quindi il throughput
  session-timeout-ms: 10000 #è il timeout oltre il quale il broker considera morto il consumer se non riceve heartbeat signals
  heartbeat-interval-ms: 3000 #ogni quanto il consumer manda heartbeat al broker: generalmente si mette 1/3 della property di sopra
  max-poll-interval-ms: 300000 #è relativo al tempo di processing dei messaggi: se il consumer per elaborare i dati impiega più di questo tempo, il coordinator lo elimina e iniziare un ribilanciamento. Ovviamente è un valore da settare in base al tempo necessario per elaborazione dei messsaggi
  max-poll-records: 500 #numero massimo di record da prendere per ogni "pool"
  max-partition-fetch-bytes-default: 1048576 #numero massimo di byte da prendere per ogni "pool"
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150 #timeout che indica il massimo tempo di attesa di un nuovo record

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true
